### ISSUE TITLE
Class 'agilesdesign\Laravel\Pseudo\Providers\PseudoServiceProvider' not found

### ISSUE THREAD

**Issue by MadMikeyB** [agilesdesign/pseudo#1]
Seems it should be 

agilesdesign\Pseudo\Providers\PseudoServiceProvider

Which is also not found... 

I think I have it working with:

`Pseudo\Providers\PseudoServiceProvider::class,`

**Comment by jrseliga** [comment]
`Pseudo\Providers\PseudoServiceProvider::class,` is correct, I changed the Namespace but forgot to update the readme.
