### ISSUE TITLE
Does this still work for 5.4?

### ISSUE THREAD

**Issue by RobbeVW** [agilesdesign/pseudo#3]
Using Laravel 5.4, whenever I try `dd(\Auth::user());` it returns `null` and not `Pseudo\Auth\Guest`.

app.php
https://gist.github.com/bcbb41afcbc8ff3e3b844eb12e4c17fc
composer.json
https://gist.github.com/db2028255b21cd8de4bc594deccf04ce

Functionality doesn't seem to work as guests are still redirected to the login route. Am I missing something? Thanks in advance.

**Comment by jrseliga** [comment]
This is compatible with Laravel 5.4. You'll need to also update the `config/auth.php` and set the `web` guard to use the driver of `pseudo`. The README was missing that instruction, but has been updated.
